### PR TITLE
Added fixes from the PR board.

### LINKED ISSUE #8: Pattern changes are not immediately reflected
For things like credit cards the pattern needs to be updated on the fly. E.g. if an amex card is detected that uses a different pattern to visa for example. 

Currently MaskedInput doesn't use setPattern to update the pattern when it changes so changing the pattern dynamically results in no changes.

### PR DESCRIPTION
**Pull request by martyphee**
Add support for updating the `mask`. Fixes #8.

Previously the cursor would go to the end of the input if you changed the mask or re-created the MaskedInput field.  So, if you have a user typing `34` and then switching the mask to `1111 111111 11111` the cursor would be positioned to the end: `34__ ______ _____^`.

This PR takes suggestions from PR #9.

### CODE REVIEW

**Comment by iamdustan** [comment]
what behavior is this intended to change or modify?

**Comment by martyphee** [comment]
@iamdustan I reopned this PR.  Looks like the suggestions from the other issues/pr's fixed the issue.

**Comment by iamdustan** [comment]
cool. how extensively did you test this, btw?

**Comment by iamdustan** [comment]
could you update your commit message to describe the code change more clearly? E.g.

```
Add support for updating the `mask`. Fixes #8
```

**Comment by martyphee** [comment]
> cool. how extensively did you test this, btw?

Right now I'm testing our use case which is rebuilding our checkout pages.  I can add it to other fields in the checkout flow.

**Comment by martyphee** [comment]
@iamdustan Do you think we'll be able to get this merged on Monday?

**Comment by iamdustan** [comment]
Could you add a test case or two and an example of this to the demo?

That’ll make it easier to test out and verify it doesn’t regress in the future. Thanks!

**Comment by martyphee** [comment]
Fair enough.  Not sure how to do the test case.  Need to see where the
cursor ends up I think.

**Comment by martyphee** [comment]
I updated the demo and added a test.  Let me know what you think.

File: tests/index-test.js [hunk 1]
```diff
@@ -46,5 +46,46 @@ describe('MaskedInput', () => {
...
+    let defaultMask = '1111 1111 1111 1111'
+    let amexMask = '1111 111111 11111'
+    let mask = defaultMask
+
+    function render() {
+      ReactDOM.render(
+          <MaskedInput
+              ref={(r) => {
+          if (r) ref = r
+        }}
```
Comment (iamdustan) [inline tests/index-test.js]: nit on the spacing here.

**Comment by iamdustan** [comment]
awesome. Thanks for adding that demo and test case, @martyphee. I’m on PTO a lot this week so won’t be able to test it myself until next week. I’ve asked @jquense to give it a look at his earliest opportunity to get this shipped. Based on his work inside React’s DOM event handling I trust him more than me anyway :)

**Comment by martyphee** [comment]
I fixed up the formatting.  @jquense if you have time to review/merge/push that would be great.  I have a outstanding PR in our project which depends on this change.

Thank you!

**Comment by jquense** [comment]
LGTM, can you please squash the commits and change the message per: https://github.com/insin/react-maskedinput/pull/53#issuecomment-220656793

**Comment by martyphee** [comment]
Done.

**Comment by martyphee** [comment]
@jquense When would you be able to do a release to npm?  Thanks for the help.

**Comment by jquense** [comment]
unfortunately no, I don't have publish rights to npm sorry!

**Comment by insin** [comment]
I just added `monastic.panic` as an npm owner - does anyone else need/want access?

**Comment by martyphee** [comment]
@insin I only need it to get this published.  I might contribute more in the future.  `martyphee`

**Comment by jquense** [comment]
ok published at 3.2.0

**Comment by martyphee** [comment]
Awesome!  Thank you!
